services:
  - type: web
    name: django-autoencoder
    env: python
    region: oregon
    plan: starter  # or free - adjust based on your needs
    buildCommand: "./build.sh"
    startCommand: "gunicorn user.wsgi:application --workers 2 --threads 4 --timeout 300 --log-level info --access-logfile - --error-logfile -"
    
    # Health check configuration
    healthCheckPath: /health/
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      
      - key: SECRET_KEY
        generateValue: true
      
      - key: DEBUG
        value: False
      
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      
      - key: DATABASE_URL
        fromDatabase:
          name: django-autoencoder-db
          property: connectionString
      
      - key: EMAIL_HOST_USER
        sync: false
      
      - key: EMAIL_HOST_PASSWORD
        sync: false
      
      # TensorFlow optimizations
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"
      
      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"
      
      # Gunicorn worker configuration
      - key: WEB_CONCURRENCY
        value: "2"

databases:
  - name: django-autoencoder-db
    databaseName: autoencoder_db
    user: autoencoder_user
    region: oregon
    plan: starter  # or free